[book]
authors = ["@danielbui12"]
language = "en"
multilingual = false
src = "src"
title = "Substrate Bitcoin-like Blockchain"

[output.html]
additional-css = ["custom/styles.css"]
additional-js = ["custom/tabs.js"]
git-repository-url = "https://github.com/openguild-labs/substrate-bitcoin"
git-repository-icon = "fa-github"
